### ISSUE TITLE
Include transport when run on CLI

### ISSUE THREAD

**Issue by phpengine** [asmblah/uniter#52]
Hi, @asmblah , how goes?

I'm having an issue when running uniter on CLI. I ran
```sudo npm install -g uniter```
 
But the require command doesn't appear to work...
```
pharaoh@pharaohbook:/tmp$ uniter -r 'require("/tmp/uniter_executor.php");'
include(/tmp/uniter_executor.php) :: No "include" transport is available for loading the module.
```
With a node version of the following
```
pharaoh@pharaohbook:/tmp$ node -v
v8.10.0
```

Thanks in advance

**Comment by asmblah** [comment]
@phpengine all good here thanks, how are you?

I believe this has been fixed in the latest beta/experimental version, so a similar issue to #53. Could you try installing the latest version of Uniter's `dotphp` package please?

Things should then behave as you expect as a workaround for now:

```shell
$ cat test.php 
<?php

print 'Hello!' . PHP_EOL;
```

```shell
$ dotphp -r 'require("./test.php");'
Hello!
```

I'm aiming to get the experimental branch of `phpruntime` merged back to master and a stable release published this weekend. This PR shows the changeset: https://github.com/uniter/phpruntime/pull/6 which is quite extensive 🙂

**Comment by phpengine** [comment]
Great that you're working on it, thanks! I'll hang on for the merge back into master

**Comment by asmblah** [comment]
Hi @phpengine - how are you?

Sorry for the huge delay here! This should now be fixed - I've finally managed to get this PR merged (https://github.com/uniter/phpruntime/pull/6), a new `phpruntime` package released and pulled into the main `uniter` package for a release. If you now try `npm install -g uniter` you should get version `2.13.0` which should have the fix for this issue (along with a huge amount of new standard library support and bug fixes etc.)

**Comment by asmblah** [comment]
Closing, as this should now be resolved as above. Feel free to reopen if there's still something broken for you here @phpengine
